spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.53/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#  jackson:
#    default-property-inclusion: non_null
server:
    context-path: /sell
wechat:
  mpAppId: wx1551c42b91835d83
  mpAppSecret: 5130bedbb2564f2c537fd7005147e306
  mchId: 123456789
  mchKey: a123456789
  keyPath: /var/xxxx/h5.p12
  notifyUrl: http://zywork.natapp1.cc/sell/pay/notify